service: serverless-ws-test

provider:
  name: aws
  runtime: python3.9
  websocketsApiName: custom-websockets-api-name
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  websocketsDescription: Custom Serverless Websockets
  region: ap-southeast-1
  environment:
    API_ENDPOINT: ${ssm:apigatewayendpoint}/${opt:stage,'dev'}
  logs:
    websocket: true

functions:
  connectionHandler:
    handler: connect.main
    events:
      - websocket:
          route: $connect
          authorizer: 
            name: auth
            identitySource:
              - 'route.request.header.auth'
      - websocket:
          route: $disconnect
    layers:
      - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:26
  defaultHandler:
    handler: default.main
    events:
      - websocket: $default #simple event definition without extra route property
    layers:
      - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:26
  customFooHandler:
    handler: custom_foo.main
    events:
      - websocket:
          route: foo # will trigger if $request.body.action === "foo"
    layers:
      - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:26
  apiGatewayHTTPBackend:
    handler: connect.main
    events:
      - httpApi:
          method: GET
          path: /
    layers:
      - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:26
  auth:
    handler: auth.main
    layers:
      - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:26

resources:
  Resources:
    gatewayid:
      Type: AWS::SSM::Parameter
      Properties:
        DataType: text
        Description: API Gateway Endpoint
        Name: apigatewayendpoint
        Type: String
        Value:
          Fn::GetAtt:
            - WebsocketsApi
            - ApiEndpoint

    routeintegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties: 
        ApiId: !Ref WebsocketsApi
        ConnectionType: INTERNET
        Description: "http integration"
        IntegrationMethod: GET
        IntegrationType: HTTP
        IntegrationUri:
          Fn::GetAtt:
            - HttpApi
            - ApiEndpoint
        RequestParameters:
          "integration.request.header.test": "context.authorizer.key"
          "integration.request.header.auth": "context.authorizer.number"

    route:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref WebsocketsApi
        RouteKey: 'bar'
        Target: !Join
          - /
          - - integrations
            - !Ref routeintegration

    CloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Path: /
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
    
    Account:
      Type: 'AWS::ApiGateway::Account'
      Properties:
        CloudWatchRoleArn: !GetAtt 
          - CloudWatchRole
          - Arn


package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
